# Generated by Django 3.1.4 on 2021-02-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_remove_tag_users'),
        ('track', '0002_auto_20210131_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='track_to_tag', to='tag.Tag'),
        ),
    ]
