# Generated by Django 3.1.4 on 2021-02-02 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_tag_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='users',
        ),
    ]
